# Generated by Django 3.2.9 on 2021-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField()),
                ('biography', models.CharField(max_length=5000)),
                ('place_of_birth', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField()),
                ('biography', models.CharField(max_length=5000)),
                ('place_of_birth', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('release_date', models.CharField(max_length=250)),
                ('poster_url', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=50000)),
                ('api_id', models.IntegerField()),
            ],
        ),
    ]
